import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/raika-project/styles/Home.module.css';
import Header from '../components/Header';
import Footer from '../components/Footer';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Mr. Ambatukam | Home Page</title>
        <meta name='description' content='Website Mr. Ambatukam' />
      </Head>
      <div className='flex flex-col'>
        
          <div className={styles.content}>
            <div className='ml-14 mt-28'>
              <div className='flex mb-16 justify-evenly'>

                <div className=''>
                  <Image src='/Ambatukam.png' width={230} height={230} alt='Profile' />
                </div>

                <div className='inline-block ml-8 font-medium'>
                  <h1 className='text-red-500'>Welcome Semuach</h1>
                  <h1 className='text-2xl'>Saya Mr. Ambatukam</h1>
                  <h1 className={styles['huruf-gede']}>Welcome L</h1>
                  <p>Lorem Ipoijfoajf ksandjsad ksdsadma sdkamdsiajdia saiudsaidsamkdadandaida asinsadjaoid asjdoaijdoisad aslkslas asldapo</p>
                </div>

              </div>

              <p>Lorem Ipoijfoajf ksandjsad ksdsadma sdkamdsiajdia saiudsaidsamkdadandaida asinsadjaoid asjdoaijdoisad aslkslas asldapo</p>
              <p>Lorem teme apa yang ku bicarakan bocah kau aku lagi ambasing oowww wwwwdwq qwwqdwqshi dksjdnan insajdsna as asn jdnsa</p>
              <p>Lorem teme apa yang ku bicarakan bocah kau aku lagi ambasing oowww wwwwdwq qwwqdwqshi dksjdnan insajdsna as asn jdnsa</p>
              <p>Lorem teme apa yang ku bicarakan bocah kau aku lagi ambasing oowww wwwwdwq qwwqdwqshi dksjdnan insajdsna as asn jdnsa</p>
              <p>Lorem teme apa yang ku bicarakan bocah kau aku lagi ambasing oowww wwwwdwq qwwqdwqshi dksjdnan insajdsna as asn jdnsa</p>
              <p>Lorem teme apa yang ku bicarakan bocah kau aku lagi ambasing oowww wwwwdwq qwwqdwqshi dksjdnan insajdsna as asn jdnsa</p>
              <Image src='/Ambatukam2.png' width={200} height={200} alt='Profile' />
              <p>Lorem teme apa yang ku bicarakan bocah kau aku lagi ambasing oowww wwwwdwq qwwqdwqshi dksjdnan insajdsna as asn jdnsa</p>
              <p>Lorem teme apa yang ku bicarakan bocah kau aku lagi ambasing oowww wwwwdwq qwwqdwqshi dksjdnan insajdsna as asn jdnsa</p>
              <p>Lorem teme apa yang ku bicarakan bocah kau aku lagi ambasing oowww wwwwdwq qwwqdwqshi dksjdnan insajdsna as asn jdnsa</p>
              <p>Lorem teme apa yang ku bicarakan bocah kau aku lagi ambasing oowww wwwwdwq qwwqdwqshi dksjdnan insajdsna as asn jdnsa</p>
              <Image src='/Ambatukam3.png' width={200} height={200} alt='Profile' />
              <p>Lorem teme apa yang ku bicarakan bocah kau aku lagi ambasing oowww wwwwdwq qwwqdwqshi dksjdnan insajdsna as asn jdnsa</p>
              <p>Lorem teme apa yang ku bicarakan bocah kau aku lagi ambasing oowww wwwwdwq qwwqdwqshi dksjdnan insajdsna as asn jdnsa</p>
              <p>Lorem teme apa yang ku bicarakan bocah kau aku lagi ambasing oowww wwwwdwq qwwqdwqshi dksjdnan insajdsna as asn jdnsa</p>
              <p>Lorem teme apa yang ku bicarakan bocah kau aku lagi ambasing oowww wwwwdwq qwwqdwqshi dksjdnan insajdsna as asn jdnsa</p>
              <p>Lorem teme apa yang ku bicarakan bocah kau aku lagi ambasing oowww wwwwdwq qwwqdwqshi dksjdnan insajdsna as asn jdnsa</p>
              <p>Lorem teme apa yang ku bicarakan bocah kau aku lagi ambasing oowww wwwwdwq qwwqdwqshi dksjdnan insajdsna as asn jdnsa</p>
            </div>
          </div>
        
      </div>
    </>
    // <>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <main className={styles.main}>
    //     <div className={styles.description}>
    //       <p>
    //         Hello Yuki, Get started by editing&nbsp;
    //         <code className={styles.code}>pages/index.js</code>
    //       </p>
    //       <div>
    //         <a
    //           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //           target="_blank"
    //           rel="noopener noreferrer"
    //         >
    //           By{' '}
    //           <Image
    //             src="/vercel.svg"
    //             alt="Vercel Logo"
    //             className={styles.vercelLogo}
    //             width={100}
    //             height={24}
    //             priority
    //           />
    //         </a>
    //       </div>
    //     </div>

    //     <div className={styles.center}>
    //       <Image
    //         className={styles.logo}
    //         src="/next.svg"
    //         alt="Next.js Logo"
    //         width={180}
    //         height={37}
    //         priority
    //       />
    //       <div className={styles.thirteen}>
    //         <Image
    //           src="/thirteen.svg"
    //           alt="13"
    //           width={40}
    //           height={31}
    //           priority
    //         />
    //       </div>
    //     </div>

    //     <div className={styles.grid}>
    //       <a
    //         href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2 className={inter.className}>
    //           Docs <span>-&gt;</span>
    //         </h2>
    //         <p className={inter.className}>
    //           Find in-depth information about Next.js features and&nbsp;API.
    //         </p>
    //       </a>

    //       <a
    //         href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2 className={inter.className}>
    //           Learn <span>-&gt;</span>
    //         </h2>
    //         <p className={inter.className}>
    //           Learn about Next.js in an interactive course with&nbsp;quizzes!
    //         </p>
    //       </a>

    //       <a
    //         href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2 className={inter.className}>
    //           Templates <span>-&gt;</span>
    //         </h2>
    //         <p className={inter.className}>
    //           Discover and deploy boilerplate example Next.js&nbsp;projects.
    //         </p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2 className={inter.className}>
    //           Deploy <span>-&gt;</span>
    //         </h2>
    //         <p className={inter.className}>
    //           Instantly deploy your Next.js site to a shareable URL
    //           with&nbsp;Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>
    // </>
  )
}
